name: simulation_page
description: Simulation page feature package with acoustic grid logic.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  l10n_service:
    path: ../../services/l10n
  core_ui:
    path: ../../core/ui
  common_helpers:
    path: ../../helpers/common
  sonalyze_webview:
    path: ../../features/sonalyze_webview

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
