services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/aal/.nginx/conf:/etc/nginx/conf.d
      - /home/aal/sonalyze/Frontend/prod/web/:/usr/share/nginx/html
      - /home/aal/.certbot/www:/var/www/certbot
      - /home/aal/.certbot/conf:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/aal/.certbot/www:/var/www/certbot
      - /home/aal/.certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
