name: recording_service
description: Raw audio recording service for Sonalyze.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.2
  record_android: ^1.4.4
  record_ios: ^1.1.4
  record_linux: ^1.2.1
  record_macos: ^1.1.2
  record_web: ^1.2.1
  record_windows: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
