name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Sonalyze server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}   # aal
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Actions->Server SSH key
          port: 22
          script_stop: true
          script: |
            set -euo pipefail

            cd /home/aal/sonalyze/Frontend

            git fetch origin main
            git checkout main
            git pull --ff-only origin main
            
            # Use Flutter from server installation
            export PATH="$PATH:/home/aal/.sdk/flutter/bin:$HOME/.pub-cache/bin"
            
            melos bootstrap
            
            flutter build web --release --output prod/web
